import { Injectable, signal } from '@angular/core';
import { StorageService } from './storage.service';

const LANG_KEY = 'staj2_language';

export const TRANSLATIONS = {
  tr: {
    // Menu & Layout
    brand_name: 'Kargo Takip Sistemi',
    dashboard: 'Dashboard',
    shipments: 'Gönderiler',
    couriers: 'Kurye Atama',
    deliveries: 'Teslimatlar',
    returns: 'İadeler',
    zones: 'Bölgeler',
    reports: 'Performans Raporu',
    audit_log: 'Denetim Kaydı',
    active_role: 'Aktif Rol',
    language: 'Dil',
    loading: 'Yükleniyor...',
    error_occurred: 'Bir hata oluştu.',
    retry: 'Tekrar Dene',
    cancel: 'Vazgeç',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    add_new: 'Yeni Ekle',
    status: 'Durum',
    actions: 'İşlemler',
    all: 'Tümü',
    no_results: 'Sonuç bulunamadı',
    search: 'Ara...',
    previous: '‹ Önceki',
    next: 'Sonraki ›',
    total_records: 'Toplam {count} kayıt',
    page_size: '{size} / sayfa',
    confirm: 'Onayla',
    data_management: 'Veri Yönetimi',
    load_demo_data: 'Örnek Veri Yükle',
    delete_all_data: 'Tüm Verileri Sil',
    simulate_error: 'Hata Ekranını Simüle Et',
    simulate_error_toast: 'Sonraki sayfa yüklemesinde hata simüle edilecek. Bir sayfayı yenileyin veya açın.',
    access_denied: 'Bu sayfaya erişim yetkiniz yok.',
    latest_actions: 'Son İşlemler',
    mark_all_read: 'Tümünü okundu işaretle',
    no_actions: 'Henüz işlem yok.',

    // Roles
    'operasyon-uzmani': 'Operasyon Uzmanı',
    'kurye-sorumlusu': 'Kurye Sorumlusu',
    'musteri-hizmetleri': 'Müşteri Hizmetleri',

    // Dashboard
    perf_dashboard: 'Performans Dashboardu',
    total_shipments: 'Toplam Gönderi',
    delivered_rate: 'Teslim Edildi Oranı',
    delayed_shipments: 'Geciken Gönderi',
    return_rate: 'İade Oranı',
    today: 'bugün',
    today_delivery: 'bugün teslim',
    en_eski: 'En eski',
    gun: 'gün',
    status_dist: 'Durum Dağılımı',
    default_sort: 'Varsayılan Sıralama',
    sort_desc: 'Kargo Sayısı: Azalan',
    sort_asc: 'Kargo Sayısı: Artan',
    total: 'Toplam',
    latest_shipments: 'Son Gönderiler',
    active_couriers: 'Aktif Kuryeler',
    capacity: 'Kapasite',
    all_zones: 'Tüm Bölgeler',
    all_times: 'Tüm Zamanlar',
    last_7_days: 'Son 7 Gün',
    last_30_days: 'Son 30 Gün',
    last_90_days: 'Son 90 Gün',

    // Shipments List
    shipment_list_title: 'Gönderi Listesi',
    create_new_shipment: 'Yeni Gönderi',
    tracking_code: 'Takip Kodu',
    recipient: 'Alıcı',
    weight: 'Ağırlık',
    created_at: 'Oluşturulma',
    all_statuses: 'Tüm Durumlar',
    newest: 'En Yeni',
    oldest: 'En Eski',
    weight_desc: 'Ağırlık (Azalan)',
    weight_asc: 'Ağırlık (Artan)',
    detail: 'Detay',
    no_shipments: 'Henüz gönderi kaydı yok',
    no_shipments_desc: 'Kendi verilerinizi girerek başlayabilir veya üstteki Veri Yönetimi menüsünden örnek veri yükleyebilirsiniz.',
    no_filtered_shipments: 'Seçilen kriterlere uyan gönderi yok',
    no_filtered_shipments_desc: 'Farklı bir bölge veya arama kriteri deneyin.',

    // Shipment Form
    new_shipment: 'Yeni Gönderi',
    edit_shipment: 'Gönderiyi Düzenle',
    recipient_address: 'Alıcı Adresi',
    select_registered_address: 'Kayıtlı adres seç',
    add_new_address: '+ Yeni adres ekle',
    select_address_placeholder: 'Adres seçin',
    address_required: 'Adres seçimi zorunludur.',
    open_address: 'Açık Adres',
    open_address_placeholder: 'Mahalle, cadde/sokak, no',
    open_address_required: 'Açık adres zorunludur.',
    max_length_150: 'En fazla 150 karakter girilebilir.',
    recipient_name: 'Alıcı Ad Soyad',
    recipient_name_required: 'Alıcı adı zorunludur.',
    min_length_3: 'En az 3 karakter girin.',
    max_length_50: 'En fazla 50 karakter girilebilir.',
    recipient_phone: 'Alıcı Telefon',
    phone_required: 'Telefon numarası zorunludur.',
    phone_invalid: 'Geçerli bir Türkiye telefon numarası girin (0 ile başlayan 11 hane).',
    max_length_15: 'En fazla 15 karakter girilebilir.',
    delivery_zone: 'Teslimat Bölgesi',
    select_zone_placeholder: 'Bölge seçin',
    zone_required: 'Bölge seçimi zorunludur.',
    weight_kg: 'Ağırlık (kg)',
    weight_required: 'Ağırlık zorunludur.',
    weight_positive: 'Ağırlık pozitif bir sayı olmalıdır.',
    weight_max: 'Maksimum ağırlık 500 kg olabilir.',
    description: 'Açıklama (opsiyonel)',
    max_length_100: 'En fazla 100 karakter girilebilir.',
    saving: 'Kaydediliyor...',

    // Shipment Detail & Tracker
    back_to_shipments: '‹ Gönderilere Dön',
    shipment_info: 'Gönderi Bilgileri',
    phone: 'Telefon',
    zone: 'Bölge',
    courier: 'Kurye',
    last_update: 'Son Güncelleme',
    not_assigned: 'Atanmadı',
    cancel_shipment: 'İptal Et',
    shipment_canceled_banner: 'Bu gönderi iptal edilmiştir.',
    status_history: 'Durum Geçmişi',
    no_history: 'Henüz durum geçmişi yok.',
    timeline_connector: '·',
    print_label: 'İrsaliye Yazdır',
    shipping_label: 'Kargo Taşıma Belgesi / İrsaliye',
    sender: 'Gönderici',
    sender_info: 'Kargo Genel Merkezi (Merkez Şube)',
    sign_recipient: 'Teslim Alan İmza',
    sign_courier: 'Kurye İmza',

    // Tracker steps
    step_created: 'Kayıt Alındı',
    step_assigned: 'Kurye Atandı',
    step_in_delivery: 'Dağıtımda',
    step_failed_delivery: 'Teslim Edilemedi',
    step_returning: 'İade Sürecinde',
    step_delivered: 'Teslim Edildi',
    step_returned: 'İade Edildi',

    // Courier Assignment
    courier_assignment_title: 'Kurye Atama',
    new_courier: 'Yeni Kurye',
    edit_courier: 'Kuryeyi Düzenle',
    courier_capacity_status: 'Kurye Kapasite Durumu',
    search_courier_placeholder: 'Kurye ara...',
    all_couriers: 'Tüm Kuryeler',
    active_couriers_opt: 'Aktif Kuryeler',
    passive_couriers_opt: 'Pasif Kuryeler',
    sort_name: 'Ad (A-Z)',
    sort_fullness: 'Doluluk (Azalan)',
    assigned_capacity: 'Atanan / Kapasite',
    fullness: 'Doluluk',
    status_badge_active: 'Aktif',
    status_badge_passive: 'Pasif',
    pasife_al: 'Pasife Al',
    aktiflestir: 'Aktifleştir',
    assigned_shipments: 'Atama Bekleyen Gönderiler',
    search_pending_placeholder: 'Takip kodu veya alıcı ara...',
    select_courier_placeholder: 'Kurye seçin',
    assign: 'Ata',
    assigned_success: 'Kurye atandı.',
    dolu: 'Dolu',

    // Courier Form
    courier_name: 'Ad Soyad',
    courier_name_required: 'Ad Soyad zorunludur.',
    daily_capacity: 'Günlük Kapasite',
    capacity_required: 'Kapasite zorunludur.',
    capacity_positive: 'Kapasite pozitif bir sayı olmalıdır.',
    capacity_integer: 'Kapasite sadece tam sayı olabilir.',
    capacity_max: 'Maksimum kapasite 200 olabilir.',
    unsaved_title: 'Değişiklikler Kaydedilmedi',
    unsaved_message: 'Formda kaydedilmemiş değişiklikler var. Çıkmak istediğinize emin misiniz?',
    unsaved_exit: 'Çık',

    // Deliveries
    deliveries_title: 'Teslimatlar',
    search_deliveries_placeholder: 'Takip kodu veya alıcı ara...',
    all_delivery_statuses: 'Tüm Teslimat Durumları',
    last_updated: 'Son Güncellenen',
    first_updated: 'İlk Güncellenen',
    proof: 'Kanıt',
    update_time: 'Güncelleme',
    proof_exists: 'Var',
    proof_none: '—',
    empty_deliveries: 'Teslimat kaydı bulunamadı',

    // Delivery Proof Section
    delivery_proof_title: 'Teslimat Kanıtı',
    delivery_recipient: 'Teslim Alan',
    signature: 'İmza',
    signature_taken: 'Alındı',
    signature_not_taken: 'Alınmadı',
    proof_note: 'Not',
    add_delivery_proof: 'Teslimat Kanıtı Ekle',
    proof_recipient_name: 'Teslim Alan Ad Soyad',
    signature_label: 'İmza alındı',
    save_proof: 'Teslimat Kanıtını Kaydet',

    // Returns
    returns_title: 'İadeler',
    search_returns_placeholder: 'Takip kodu veya neden ara...',
    all_statuses_returns: 'Tüm Durumlar',
    reason: 'Neden',
    request_time: 'Oluşturulma',
    approve: 'Onayla',
    reject: 'Reddet',
    complete: 'Tamamla',
    empty_returns: 'İade talebi bulunmuyor',
    return_status_dialog_title: 'İade Talebi Durumu',
    return_status_dialog_message: 'İade talebi "{status}" olarak işaretlenecek. Onaylıyor musunuz?',
    open_return_request: 'İade Talebi Aç',

    // Zones
    zones_title: 'Bölgeler',
    search_zones_placeholder: 'Bölge, il veya ilçe ara...',
    all_zones_opt: 'Tüm Bölgeler',
    active_zones_opt: 'Aktif Bölgeler',
    passive_zones_opt: 'Pasif Bölgeler',
    zone_name: 'Bölge Adı',
    zone_required_error: 'Zorunlu alan.',
    max_length_50_error: 'En fazla 50 karakter girilebilir.',
    province: 'İl',
    select_province_placeholder: 'İl seçin',
    district: 'İlçe',
    select_district_placeholder: 'İlçe seçin',
    select_province_first: 'Önce il seçin',
    empty_zones: 'Henüz bölge tanımlı değil',
    delete_zone_confirm_title: 'Bölgeyi Sil',
    delete_zone_confirm_message: '"{name}" bölgesi kalıcı olarak silinecek. Onaylıyor musunuz?',
    delete_zone_active_shipments: 'Bu bölgede {count} adet aktif gönderi bulunduğundan bölge silinemez!',
    delete_zone_assigned_couriers: 'Bu bölgeye atanmış {count} adet kurye bulunduğundan bölge silinemez!',
    delete_zone_success: 'Bölge başarıyla silindi.',
    deactivate_zone_confirm_title: 'Bölgeyi Pasife Al',
    deactivate_zone_confirm_message_active: '"{name}" bölgesinde {count} aktif gönderi bulunuyor! Pasife alırsa bu gönderiler etkilenebilir. Devam etmek istediğinize emin misiniz?',
    deactivate_zone_confirm_message: '"{name}" bölgesi pasife alınacak. Onaylıyor musunuz?',

    // Reports
    courier_perf_report: 'Kurye Performans Raporu',
    average_delivery_time: 'Ort. Teslim Süresi',
    delay_rate: 'Gecikme Oranı',
    success_rate: 'Başarı Oranı',
    hours: 'saat',

    // Audit Log
    audit_log_title: 'Denetim Kaydı',
    actor: 'İşlemi Yapan',
    description_label: 'Açıklama',
    timestamp: 'Zaman Damgası',

    // Shipment Status Translation
    status_olusturuldu: 'Kayıt Alındı',
    status_kurye_atandi: 'Kurye Atandı',
    status_dagitimda: 'Dağıtımda',
    status_teslim_edildi: 'Teslim Edildi',
    status_teslim_edilemedi: 'Teslim Edilemedi',
    status_iade_talebi: 'İade Talebi Açıldı',
    status_iade_edildi: 'İade Edildi',
    status_iptal_edildi: 'İptal Edildi',

    // Return Status Translation
    return_status_beklemede: 'Beklemede',
    return_status_onaylandi: 'Onaylandı',
    return_status_reddedildi: 'Reddedildi',
    return_status_tamamlandi: 'Tamamlandı',

    // General Toasts / Dialogs
    item_saved: 'Kaydedildi.',
    item_deleted: 'Silindi.',
    error_saving: 'Kaydedilirken bir hata oluştu.',
    error_deleting: 'Silinirken bir hata oluştu.',
    dialog_confirm_title: 'Onay',
    dialog_confirm_message: 'Bu işlemi onaylıyor musunuz?',
    description_required: 'Açıklama alanı boş bırakılamaz.',
    load_demo_confirm_title: 'Örnek Veri Yükle',
    load_demo_confirm_message: 'Sistem; örnek gönderi, kurye, bölge ve iade kayıtlarıyla doldurulacak. Devam edilsin mi?',
    delete_all_confirm_title: 'Tüm Verileri Sil',
    delete_all_confirm_message: 'Bu işlem geri alınamaz. Tüm gönderiler, kuryeler, bölgeler, adresler ve audit log kalıcı olarak silinecek.',
    demo_data_loaded: 'Örnek veri yüklendi.',
    all_data_deleted: 'Tüm veriler silindi.',

    // Audit Log Actions
    action_kurye_kaydet: 'Kurye Kaydet / Güncelle',
    action_kurye_durum: 'Kurye Aktiflik Değişimi',
    action_kurye_sil: 'Kurye Silme',
    action_iade_durum: 'İade Talebi Güncelleme',
    action_adres_olustur: 'Adres Tanımlama',
    action_bolge_kaydet: 'Bölge Kaydet / Güncelle',
    action_bolge_durum: 'Bölge Aktiflik Değişimi',
    action_bolge_sil: 'Bölge Silme',
    action_musteri_notu: 'Müşteri Notu Ekleme',
    action_ornek_veri_yukle: 'Örnek Veri Yükleme',
    action_veri_sil: 'Sistem Sıfırlama',
    action_gonderi_olustur: 'Gönderi Oluşturma',
    action_gonderi_guncelle: 'Gönderi Bilgisi Güncelleme',
    action_kurye_atama: 'Kurye Atama',
    action_durum_degisikligi: 'Gönderi Durum Güncellemesi',
    action_teslimat_kaniti: 'Teslimat Kanıtı Ekleme',

    // Additional keys for Dashboard
    no_filtered_shipments_dashboard_desc: 'Farklı bir bölge veya tarih aralığı deneyin.',
    no_shipments_yet: 'Henüz gönderi yok.',
    most_active_couriers: 'En Aktif Kuryeler',
    no_assignments_yet: 'Henüz atama yapılmadı.',
    busiest_zones: 'En Yoğun Bölgeler',
    no_zone_data_yet: 'Henüz bölge verisi yok.',
    latest_audit_log: 'Son Audit Log',
    no_actions_yet: 'Henüz işlem kaydı yok.',
    error_loading_dashboard: 'Dashboard verileri yüklenirken bir hata oluştu.',
    view_all: 'Tümünü Gör',

    // Additional keys for Shipment List
    download_csv: 'CSV İndir',
    upload_bulk_csv: 'Toplu CSV Yükle',
    sort_tracking_code: 'Takip Kodu (A-Z)',
    no_results_desc: 'Arama veya filtre kriterlerinizi değiştirmeyi deneyin.',
    search_shipment_title: 'Bir gönderi arayın',
    search_shipment_desc: 'Müşteri hizmetleri görünümünde kayıtlar listelenmez; takip kodu veya alıcı adı ile arama yapın.',
    error_loading_shipments: 'Gönderiler yüklenirken bir hata oluştu.',
    no_export_data: 'Dışarı aktarılacak kargo bulunamadı.',
    csv_export_success: 'Kargo listesi CSV olarak indirildi.',
    csv_invalid_file: 'Yüklenen CSV dosyası boş veya geçersiz.',
    csv_bulk_import_success: '{count} adet gönderi toplu olarak başarıyla yüklendi.',
    csv_bulk_import_errors: '{count} adet satır geçersiz veri nedeniyle yüklenemedi.',
    csv_parsing_error: 'CSV ayrıştırılırken beklenmeyen bir hata oluştu.',
    bulk_csv_zone_delivery: '{zone} Bölge Teslimatı (Toplu CSV)',

    // Additional keys for Shipment Form
    shipment_not_found: 'Gönderi bulunamadı.',
    shipment_updated: 'Gönderi güncellendi.',
    shipment_created_code: 'Gönderi oluşturuldu: {code}',
    error_saving_try_again: 'Kayıt sırasında bir hata oluştu, lütfen tekrar deneyin.',

    // Additional keys for Shipment Detail
    assign_courier: 'Kurye Ata',
    active_courier_suitable_for_zone: 'Bölgeye uygun aktif kurye',
    no_suitable_courier_found: 'Bu bölgede uygun aktif kurye bulunamadı.',
    note_optional: 'Not (opsiyonel)',
    status_actions: 'Durum İşlemleri',
    mark_as_status: '{status} Olarak İşaretle',
    add_customer_note: 'Müşteri Notu Ekle',
    customer_note_info: 'Müşteri hizmetleri durumu değiştiremez; yalnızca gönderiye not düşebilir.',
    save_note: 'Notu Kaydet',
    select_courier_required: 'Lütfen bir kurye seçin.',
    assign_courier_confirm_message: 'Bu gönderi "{name}" kuryesine atanacak. Onaylıyor musunuz?',
    courier_assignment_failed: 'Kurye ataması başarısız oldu.',
    add_proof_first: 'Önce teslimat kanıtı ekleyin.',
    status_change_title: 'Durum Değişikliği',
    status_change_message: 'Gönderi durumu "{status}" olarak güncellenecek. Onaylıyor musunuz?',
    update_status: 'Durumu Güncelle',
    status_updated: 'Durum güncellendi.',
    status_update_failed: 'Durum güncellenemedi.',
    proof_recipient_name_required: 'Teslim alan kişinin adı zorunludur.',
    proof_saved_success: 'Teslimat kanıtı kaydedildi. Şimdi durumu "Teslim Edildi" yapabilirsiniz.',
    proof_save_failed: 'Teslimat kanıtı kaydedilemedi.',
    return_request_title: 'İade Talebi',
    return_request_confirm_message: 'Bu gönderi için iade talebi açılacak. Onaylıyor musunuz?',
    return_request_created: 'İade talebi oluşturuldu.',
    return_request_create_failed: 'İade talebi oluşturulamadı.',
    cancel_shipment_title: 'Gönderiyi İptal Et',
    cancel_shipment_confirm_message: 'İptal edilen gönderi tekrar aktifleştirilemez. Onaylıyor musunuz?',
    shipment_canceled: 'Gönderi iptal edildi.',
    shipment_cancel_failed: 'Gönderi iptal edilemedi.',
    note_required: 'Not alanı boş olamaz.',
    note_saved: 'Notunuz kaydedildi.',
    note_save_failed: 'Not kaydedilemedi.',

    // Additional keys for Courier Assignment
    no_couriers_matching: 'Kriterlere uygun kurye bulunmuyor.',
    select_courier_header: 'Kurye Seç',
    no_pending_assignments_matching: 'Bekleyen atamalarda kriterlerinize uyan kayıt bulunmuyor.',
    error_loading_courier_assignment: 'Kurye atama verileri yüklenirken bir hata oluştu.',
    assign_courier_shipment_confirm_message: '{code} gönderisi "{name}" kuryesine atanacak. Onaylıyor musunuz?',
    courier_assigned_for_shipment: '{code} için kurye atandı.',
    courier_updated: 'Kurye güncellendi.',
    courier_created: 'Kurye oluşturuldu.',
    error_saving_courier: 'Kurye kaydedilirken bir hata oluştu.',
    deactivate_courier_title: 'Kuryeyi Pasife Al',
    activate_courier_title: 'Kuryeyi Aktifleştir',
    deactivate_courier_confirm: '"{name}" pasife alınacak. Onaylıyor musunuz?',
    activate_courier_confirm: '"{name}" aktifleştirilecek. Onaylıyor musunuz?',
    courier_status_updated: 'Kurye durumu güncellendi.',
    courier_status_update_failed: 'Kurye durumu güncellenemedi.',
    cannot_delete_courier_active_shipments: 'Bu kuryenin {count} adet aktif dağıtım/atama kaydı bulunduğundan silinemez!',
    delete_courier_title: 'Kuryeyi Sil',
    delete_courier_confirm_message: '"{name}" kuryesi kalıcı olarak silinecek. Onaylıyor musunuz?',
    courier_deleted_success: 'Kurye başarıyla silindi.',
    courier_delete_failed: 'Kurye silinirken bir hata oluştu.',

    // Additional keys for Deliveries
    error_loading_deliveries: 'Teslimatlar yüklenirken bir hata oluştu.',

    // Additional keys for Returns
    error_loading_returns: 'İade talepleri yüklenirken bir hata oluştu.',
    return_request_updated: 'İade talebi güncellendi.',
    return_request_update_failed: 'İade talebi güncellenemedi.',

    // Additional keys for Zones
    add_new_zone: 'Yeni Bölge',
    sort_province: 'İl (A-Z)',
    new_zone: 'Yeni Bölge',
    edit_zone: 'Bölgeyi Düzenle',
    name_label: 'Ad',
    error_loading_zones: 'Bölgeler yüklenirken bir hata oluştu.',
    zone_updated: 'Bölge güncellendi.',
    zone_created: 'Bölge oluşturuldu.',
    error_saving_zone: 'Bölge kaydedilirken bir hata oluştu.',
    activate_zone_confirm_message: '"{name}" bölgesi aktifleştirilecek. Onaylıyor musunuz?',
    activate_zone_confirm_title: 'Bölgeyi Aktifleştir',
    zone_status_updated: 'Bölge durumu güncellendi.',
    zone_status_update_failed: 'Bölge durumu güncellenemedi.',
    zone_delete_failed: 'Bölge silinirken bir hata oluştu.',

    // Additional keys for Reports
    reports_title: 'Raporlar',
    print_report: 'Rapor Yazdır',
    delayed: 'Geciken',
    return_label: 'İade',
    zone_based_performance: 'Bölge Bazlı Performans',
    delivery_rate: 'Teslim Oranı',
    no_zone_data: 'Bölge verisi yok',
    courier_based_performance: 'Kurye Bazlı Performans',
    no_courier_data: 'Kurye verisi yok',
    error_loading_reports: 'Rapor verileri yüklenirken bir hata oluştu.',
    days: 'gün',

    // Additional keys for Audit Log
    search_description_placeholder: 'Açıklamada ara...',
    all_action_types: 'Tüm İşlem Tipleri',
    sort_role: 'Rol (A-Z)',
    time: 'Zaman',
    role_header: 'Rol',
    action_header: 'İşlem',
    old_new_header: 'Eski → Yeni',
    no_actions_found: 'İşlem kaydı bulunamadı',
    no_actions_desc: 'Filtreyi değiştirin veya bir işlem yaptıktan sonra tekrar bakın.',
    action_detail_title: 'İşlem Detayı',
    close: 'Kapat',
    action_type: 'İşlem Tipi',
    old_value: 'Eski Değer',
    new_value: 'Yeni Değer',
    target_id: 'Hedef ID'
  },
  en: {
    // Menu & Layout
    brand_name: 'Cargo Tracking System',
    dashboard: 'Dashboard',
    shipments: 'Shipments',
    couriers: 'Courier Assignment',
    deliveries: 'Deliveries',
    returns: 'Returns',
    zones: 'Zones',
    reports: 'Performance Report',
    audit_log: 'Audit Log',
    active_role: 'Active Role',
    language: 'Language',
    loading: 'Loading...',
    error_occurred: 'An error occurred.',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add_new: 'Add New',
    status: 'Status',
    actions: 'Actions',
    all: 'All',
    no_results: 'No results found',
    search: 'Search...',
    previous: '‹ Previous',
    next: 'Next ›',
    total_records: 'Total {count} records',
    page_size: '{size} / page',
    confirm: 'Confirm',
    data_management: 'Data Management',
    load_demo_data: 'Load Demo Data',
    delete_all_data: 'Delete All Data',
    simulate_error: 'Simulate Error State',
    simulate_error_toast: 'An error will be simulated on the next page load. Reload or open a page.',
    access_denied: 'You do not have permission to access this page.',
    latest_actions: 'Latest Actions',
    mark_all_read: 'Mark all as read',
    no_actions: 'No actions logged yet.',

    // Roles
    'operasyon-uzmani': 'Operation Specialist',
    'kurye-sorumlusu': 'Courier Supervisor',
    'musteri-hizmetleri': 'Customer Relations',

    // Dashboard
    perf_dashboard: 'Performance Dashboard',
    total_shipments: 'Total Shipments',
    delivered_rate: 'Delivered Rate',
    delayed_shipments: 'Delayed Shipments',
    return_rate: 'Return Rate',
    today: 'today',
    today_delivery: 'today delivered',
    en_eski: 'Oldest',
    gun: 'days',
    status_dist: 'Status Distribution',
    default_sort: 'Default Sort',
    sort_desc: 'Cargo Count: Descending',
    sort_asc: 'Cargo Count: Ascending',
    total: 'Total',
    latest_shipments: 'Latest Shipments',
    active_couriers: 'Active Couriers',
    capacity: 'Capacity',
    all_zones: 'All Zones',
    all_times: 'All Times',
    last_7_days: 'Last 7 Days',
    last_30_days: 'Last 30 Days',
    last_90_days: 'Last 90 Days',

    // Shipments List
    shipment_list_title: 'Shipment List',
    create_new_shipment: 'New Shipment',
    tracking_code: 'Tracking Code',
    recipient: 'Recipient',
    weight: 'Weight',
    created_at: 'Created At',
    all_statuses: 'All Statuses',
    newest: 'Newest',
    oldest: 'Oldest',
    weight_desc: 'Weight (Desc)',
    weight_asc: 'Weight (Asc)',
    detail: 'Detail',
    no_shipments: 'No shipment records yet',
    no_shipments_desc: 'You can start by entering your own data or load demo dataset from Data Management menu above.',
    no_filtered_shipments: 'No shipments match selected criteria',
    no_filtered_shipments_desc: 'Try a different zone or search query.',

    // Shipment Form
    new_shipment: 'New Shipment',
    edit_shipment: 'Edit Shipment',
    recipient_address: 'Recipient Address',
    select_registered_address: 'Select registered address',
    add_new_address: '+ Add new address',
    select_address_placeholder: 'Select address',
    address_required: 'Address selection is required.',
    open_address: 'Street Address',
    open_address_placeholder: 'Neighborhood, street, no',
    open_address_required: 'Street address is required.',
    max_length_150: 'Maximum 150 characters allowed.',
    recipient_name: 'Recipient Name',
    recipient_name_required: 'Recipient name is required.',
    min_length_3: 'Enter at least 3 characters.',
    max_length_50: 'Maximum 50 characters allowed.',
    recipient_phone: 'Recipient Phone',
    phone_required: 'Phone number is required.',
    phone_invalid: 'Enter a valid Turkey phone number (11 digits starting with 0).',
    max_length_15: 'Maximum 15 characters allowed.',
    delivery_zone: 'Delivery Zone',
    select_zone_placeholder: 'Select zone',
    zone_required: 'Zone selection is required.',
    weight_kg: 'Weight (kg)',
    weight_required: 'Weight is required.',
    weight_positive: 'Weight must be a positive number.',
    weight_max: 'Maximum weight can be 500 kg.',
    description: 'Description (optional)',
    max_length_100: 'Maximum 100 characters allowed.',
    saving: 'Saving...',

    // Shipment Detail & Tracker
    back_to_shipments: '‹ Back to Shipments',
    shipment_info: 'Shipment Details',
    phone: 'Phone',
    zone: 'Zone',
    courier: 'Courier',
    last_update: 'Last Update',
    not_assigned: 'Not Assigned',
    cancel_shipment: 'Cancel',
    shipment_canceled_banner: 'This shipment has been canceled.',
    status_history: 'Status History',
    no_history: 'No status history yet.',
    timeline_connector: '·',
    print_label: 'Print Waybill',
    shipping_label: 'Shipping Waybill / Label',
    sender: 'Sender',
    sender_info: 'Cargo Headquarters (Main Branch)',
    sign_recipient: 'Recipient Signature',
    sign_courier: 'Courier Signature',

    // Tracker steps
    step_created: 'Received',
    step_assigned: 'Assigned',
    step_in_delivery: 'In Delivery',
    step_failed_delivery: 'Failed Delivery',
    step_returning: 'Returning',
    step_delivered: 'Delivered',
    step_returned: 'Returned',

    // Courier Assignment
    courier_assignment_title: 'Courier Assignment',
    new_courier: 'New Courier',
    edit_courier: 'Edit Courier',
    courier_capacity_status: 'Courier Capacity Status',
    search_courier_placeholder: 'Search courier...',
    all_couriers: 'All Couriers',
    active_couriers_opt: 'Active Couriers',
    passive_couriers_opt: 'Passive Couriers',
    sort_name: 'Name (A-Z)',
    sort_fullness: 'Fullness (Desc)',
    assigned_capacity: 'Assigned / Capacity',
    fullness: 'Fullness',
    status_badge_active: 'Active',
    status_badge_passive: 'Passive',
    pasife_al: 'Deactivate',
    aktiflestir: 'Activate',
    assigned_shipments: 'Pending Assignments',
    search_pending_placeholder: 'Search tracking code or recipient...',
    select_courier_placeholder: 'Select courier',
    assign: 'Assign',
    assigned_success: 'Courier assigned.',
    dolu: 'Full',

    // Courier Form
    courier_name: 'Full Name',
    courier_name_required: 'Full name is required.',
    daily_capacity: 'Daily Capacity',
    capacity_required: 'Capacity is required.',
    capacity_positive: 'Capacity must be a positive number.',
    capacity_integer: 'Capacity must be an integer.',
    capacity_max: 'Maximum capacity can be 200.',
    unsaved_title: 'Unsaved Changes',
    unsaved_message: 'There are unsaved changes in the form. Are you sure you want to exit?',
    unsaved_exit: 'Exit',

    // Deliveries
    deliveries_title: 'Deliveries',
    search_deliveries_placeholder: 'Search tracking code or recipient...',
    all_delivery_statuses: 'All Delivery Statuses',
    last_updated: 'Last Updated',
    first_updated: 'First Updated',
    proof: 'Proof',
    update_time: 'Update Time',
    proof_exists: 'Yes',
    proof_none: '—',
    empty_deliveries: 'No delivery records found',

    // Delivery Proof Section
    delivery_proof_title: 'Delivery Proof',
    delivery_recipient: 'Received By',
    signature: 'Signature',
    signature_taken: 'Taken',
    signature_not_taken: 'Not Taken',
    proof_note: 'Note',
    add_delivery_proof: 'Add Delivery Proof',
    proof_recipient_name: 'Recipient Full Name',
    signature_label: 'Signature taken',
    save_proof: 'Save Delivery Proof',

    // Returns
    returns_title: 'Returns',
    search_returns_placeholder: 'Search tracking code or reason...',
    all_statuses_returns: 'All Statuses',
    reason: 'Reason',
    request_time: 'Requested At',
    approve: 'Approve',
    reject: 'Reject',
    complete: 'Complete',
    empty_returns: 'No return requests found',
    return_status_dialog_title: 'Return Request Status',
    return_status_dialog_message: 'Return request will be marked as "{status}". Do you confirm?',
    open_return_request: 'Open Return Request',

    // Zones
    zones_title: 'Zones',
    search_zones_placeholder: 'Search zone, province or district...',
    all_zones_opt: 'All Zones',
    active_zones_opt: 'Active Zones',
    passive_zones_opt: 'Passive Zones',
    zone_name: 'Zone Name',
    zone_required_error: 'Required field.',
    max_length_50_error: 'Maximum 50 characters allowed.',
    province: 'Province',
    select_province_placeholder: 'Select province',
    district: 'District',
    select_district_placeholder: 'Select district',
    select_province_first: 'Select province first',
    empty_zones: 'No zones defined yet',
    delete_zone_confirm_title: 'Delete Zone',
    delete_zone_confirm_message: 'Zone "{name}" will be permanently deleted. Do you confirm?',
    delete_zone_active_shipments: 'Cannot delete zone because it has {count} active shipments!',
    delete_zone_assigned_couriers: 'Cannot delete zone because it has {count} assigned couriers!',
    delete_zone_success: 'Zone successfully deleted.',
    deactivate_zone_confirm_title: 'Deactivate Zone',
    deactivate_zone_confirm_message_active: 'There are {count} active shipments in zone "{name}"! Deactivating this zone may affect them. Are you sure you want to continue?',
    deactivate_zone_confirm_message: 'Zone "{name}" will be deactivated. Do you confirm?',

    // Reports
    courier_perf_report: 'Courier Performance Report',
    average_delivery_time: 'Avg. Delivery Time',
    delay_rate: 'Delay Rate',
    success_rate: 'Success Rate',
    hours: 'hours',

    // Audit Log
    audit_log_title: 'Audit Log',
    actor: 'Actor',
    description_label: 'Description',
    timestamp: 'Timestamp',

    // Shipment Status Translation
    status_olusturuldu: 'Received',
    status_kurye_atandi: 'Courier Assigned',
    status_dagitimda: 'In Delivery',
    status_teslim_edildi: 'Delivered',
    status_teslim_edilemedi: 'Failed Delivery',
    status_iade_talebi: 'Return Initiated',
    status_iade_edildi: 'Returned',
    status_iptal_edildi: 'Canceled',

    // Return Status Translation
    return_status_beklemede: 'Pending',
    return_status_onaylandi: 'Approved',
    return_status_reddedildi: 'Rejected',
    return_status_tamamlandi: 'Completed',

    // General Toasts / Dialogs
    item_saved: 'Saved.',
    item_deleted: 'Deleted.',
    error_saving: 'An error occurred while saving.',
    error_deleting: 'An error occurred while deleting.',
    dialog_confirm_title: 'Confirmation',
    dialog_confirm_message: 'Do you confirm this action?',
    description_required: 'Description cannot be empty.',
    load_demo_confirm_title: 'Load Demo Data',
    load_demo_confirm_message: 'The system will be populated with sample shipments, couriers, zones, and return records. Do you want to continue?',
    delete_all_confirm_title: 'Delete All Data',
    delete_all_confirm_message: 'This action cannot be undone. All shipments, couriers, zones, addresses, and audit logs will be permanently deleted.',
    demo_data_loaded: 'Sample data loaded successfully.',
    all_data_deleted: 'All data successfully deleted.',

    // Audit Log Actions
    action_kurye_kaydet: 'Create / Update Courier',
    action_kurye_durum: 'Toggle Courier Status',
    action_kurye_sil: 'Delete Courier',
    action_iade_durum: 'Update Return Request',
    action_adres_olustur: 'Define Address',
    action_bolge_kaydet: 'Create / Update Zone',
    action_bolge_durum: 'Toggle Zone Status',
    action_bolge_sil: 'Delete Zone',
    action_musteri_notu: 'Add Customer Note',
    action_ornek_veri_yukle: 'Load Demo Data',
    action_veri_sil: 'Reset System Data',
    action_gonderi_olustur: 'Create Shipment',
    action_gonderi_guncelle: 'Update Shipment Details',
    action_kurye_atama: 'Assign Courier',
    action_durum_degisikligi: 'Update Shipment Status',
    action_teslimat_kaniti: 'Save Delivery Proof',

    // Additional keys for Dashboard
    no_filtered_shipments_dashboard_desc: 'Try a different zone or date range.',
    no_shipments_yet: 'No shipments yet.',
    most_active_couriers: 'Most Active Couriers',
    no_assignments_yet: 'No assignments yet.',
    busiest_zones: 'Busiest Zones',
    no_zone_data_yet: 'No zone data yet.',
    latest_audit_log: 'Latest Audit Log',
    no_actions_yet: 'No actions yet.',
    error_loading_dashboard: 'An error occurred while loading dashboard data.',
    view_all: 'View All',

    // Additional keys for Shipment List
    download_csv: 'Download CSV',
    upload_bulk_csv: 'Bulk CSV Upload',
    sort_tracking_code: 'Tracking Code (A-Z)',
    no_results_desc: 'Try changing your search or filter criteria.',
    search_shipment_title: 'Search for a shipment',
    search_shipment_desc: 'In customer services view, records are not listed; search by tracking code or recipient name.',
    error_loading_shipments: 'An error occurred while loading shipments.',
    no_export_data: 'No cargo found to export.',
    csv_export_success: 'Cargo list downloaded as CSV.',
    csv_invalid_file: 'Uploaded CSV file is empty or invalid.',
    csv_bulk_import_success: '{count} shipments successfully imported in bulk.',
    csv_bulk_import_errors: '{count} rows could not be loaded due to invalid data.',
    csv_parsing_error: 'An unexpected error occurred while parsing the CSV.',
    bulk_csv_zone_delivery: '{zone} Zone Delivery (Bulk CSV)',

    // Additional keys for Shipment Form
    shipment_not_found: 'Shipment not found.',
    shipment_updated: 'Shipment updated.',
    shipment_created_code: 'Shipment created: {code}',
    error_saving_try_again: 'An error occurred during saving, please try again.',

    // Additional keys for Shipment Detail
    assign_courier: 'Assign Courier',
    active_courier_suitable_for_zone: 'Active courier suitable for zone',
    no_suitable_courier_found: 'No suitable active courier found in this zone.',
    note_optional: 'Note (optional)',
    status_actions: 'Status Actions',
    mark_as_status: 'Mark as {status}',
    add_customer_note: 'Add Customer Note',
    customer_note_info: 'Customer service cannot change the status; they can only add a note to the shipment.',
    save_note: 'Save Note',
    select_courier_required: 'Please select a courier.',
    assign_courier_confirm_message: 'This shipment will be assigned to courier "{name}". Do you confirm?',
    courier_assignment_failed: 'Courier assignment failed.',
    add_proof_first: 'Please add delivery proof first.',
    status_change_title: 'Status Change',
    status_change_message: 'Shipment status will be updated to "{status}". Do you confirm?',
    update_status: 'Update Status',
    status_updated: 'Status updated.',
    status_update_failed: 'Status could not be updated.',
    proof_recipient_name_required: 'The name of the person receiving is required.',
    proof_saved_success: 'Delivery proof saved. You can now set the status to "Delivered".',
    proof_save_failed: 'Delivery proof could not be saved.',
    return_request_title: 'Return Request',
    return_request_confirm_message: 'A return request will be opened for this shipment. Do you confirm?',
    return_request_created: 'Return request created.',
    return_request_create_failed: 'Return request could not be created.',
    cancel_shipment_title: 'Cancel Shipment',
    cancel_shipment_confirm_message: 'Canceled shipment cannot be reactivated. Do you confirm?',
    shipment_canceled: 'Shipment canceled.',
    shipment_cancel_failed: 'Shipment could not be canceled.',
    note_required: 'Note field cannot be empty.',
    note_saved: 'Your note has been saved.',
    note_save_failed: 'Note could not be saved.',

    // Additional keys for Courier Assignment
    no_couriers_matching: 'No couriers matching the criteria.',
    select_courier_header: 'Select Courier',
    no_pending_assignments_matching: 'No pending assignments matching the criteria.',
    error_loading_courier_assignment: 'An error occurred while loading courier assignment data.',
    assign_courier_shipment_confirm_message: 'Shipment {code} will be assigned to courier "{name}". Do you confirm?',
    courier_assigned_for_shipment: 'Courier assigned for {code}.',
    courier_updated: 'Courier updated.',
    courier_created: 'Courier created.',
    error_saving_courier: 'An error occurred while saving the courier.',
    deactivate_courier_title: 'Deactivate Courier',
    activate_courier_title: 'Activate Courier',
    deactivate_courier_confirm: '"{name}" will be deactivated. Do you confirm?',
    activate_courier_confirm: '"{name}" will be activated. Do you confirm?',
    courier_status_updated: 'Courier status updated.',
    courier_status_update_failed: 'Courier status could not be updated.',
    cannot_delete_courier_active_shipments: 'Cannot delete courier because they have {count} active delivery/assignment records!',
    delete_courier_title: 'Delete Courier',
    delete_courier_confirm_message: 'Courier "{name}" will be permanently deleted. Do you confirm?',
    courier_deleted_success: 'Courier successfully deleted.',
    courier_delete_failed: 'An error occurred while deleting the courier.',

    // Additional keys for Deliveries
    error_loading_deliveries: 'An error occurred while loading deliveries.',

    // Additional keys for Returns
    error_loading_returns: 'An error occurred while loading return requests.',
    return_request_updated: 'Return request updated.',
    return_request_update_failed: 'Return request could not be updated.',

    // Additional keys for Zones
    add_new_zone: 'New Zone',
    sort_province: 'Province (A-Z)',
    new_zone: 'New Zone',
    edit_zone: 'Edit Zone',
    name_label: 'Name',
    error_loading_zones: 'An error occurred while loading zones.',
    zone_updated: 'Zone updated.',
    zone_created: 'Zone created.',
    error_saving_zone: 'An error occurred while saving the zone.',
    activate_zone_confirm_message: 'Zone "{name}" will be activated. Do you confirm?',
    activate_zone_confirm_title: 'Activate Zone',
    zone_status_updated: 'Zone status updated.',
    zone_status_update_failed: 'Zone status could not be updated.',
    zone_delete_failed: 'An error occurred while deleting the zone.',

    // Additional keys for Reports
    reports_title: 'Reports',
    print_report: 'Print Report',
    delayed: 'Delayed',
    return_label: 'Return',
    zone_based_performance: 'Zone Based Performance',
    delivery_rate: 'Delivery Rate',
    no_zone_data: 'No zone data',
    courier_based_performance: 'Courier Based Performance',
    no_courier_data: 'No courier data',
    error_loading_reports: 'An error occurred while loading report data.',
    days: 'days',

    // Additional keys for Audit Log
    search_description_placeholder: 'Search in description...',
    all_action_types: 'All Action Types',
    sort_role: 'Role (A-Z)',
    time: 'Time',
    role_header: 'Role',
    action_header: 'Action',
    old_new_header: 'Old → New',
    no_actions_found: 'No action logs found',
    no_actions_desc: 'Change the filter or look again after performing an action.',
    action_detail_title: 'Action Detail',
    close: 'Close',
    action_type: 'Action Type',
    old_value: 'Old Value',
    new_value: 'New Value',
    target_id: 'Target ID'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly currentLang = signal<'tr' | 'en'>(
    this.storage.read<'tr' | 'en'>(LANG_KEY, 'tr')
  );

  constructor(private storage: StorageService) {
    // <html lang> aktif dile eşitlensin: CSS text-transform ve ekran okuyucular doğru dili kullanır.
    this.htmlLangGuncelle(this.currentLang());
  }

  setLanguage(lang: 'tr' | 'en'): void {
    this.currentLang.set(lang);
    this.storage.write(LANG_KEY, lang);
    this.htmlLangGuncelle(lang);
  }

  private htmlLangGuncelle(lang: 'tr' | 'en'): void {
    document.documentElement.lang = lang;
  }

  translate(key: string, params?: Record<string, string | number>): string {
    const lang = this.currentLang();
    const dictionary = TRANSLATIONS[lang] as Record<string, string>;
    let text = dictionary[key] || TRANSLATIONS['tr'][key as keyof typeof TRANSLATIONS['tr']] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(`{${paramKey}}`, String(paramValue));
      });
    }

    return text;
  }
}
